FrontEnd/App.config
FrontEnd/Properties/Settings.Designer.cs
FrontEnd/Properties/Settings.settings
FrontEnd/models/EmployeeModel.cs
FrontEnd/webconnection.cs

Fixed the login
added employeeModel
updated the url path

fixed Login

---

FrontEnd/frmTransaction.cs

removed unused imports from frm transaction

Front end backend connection

---

FrontEnd/frmDryCleaning.cs
FrontEnd/frmTransaction.cs

fixed drycleaning form

---

FrontEnd/DataAccess.cs
backend/pos-core-api/Controllers/TransactionController.cs

Verify controllers

---

FrontEnd/DataAccess.cs
FrontEnd/frmDiscount.cs
FrontEnd/frmLogin.cs
FrontEnd/frmTransaction.Designer.cs
FrontEnd/frmTransaction.cs
shared/Transaction/Item.cs
shared/Transaction/Transaction.cs

Fixed taxes
Fixed percent in description
Changed the name the of tax and discount text box adn populate them.
remove msgbox on login
Fixed percent discount
Fixed Convert to Item

Fixed stuff

---

FrontEnd/frmSetting.Designer.cs
FrontEnd/frmSetting.cs

Added Check box

---

FrontEnd/frmSetting.Designer.cs

Added General and Reports tabs

Added tabs to settings form

---

FrontEnd/frmLookup.Designer.cs
FrontEnd/frmLookup.cs

Added a checkbox on the Lookup form to allow a user to only show items that have inventory.

Added ability to only show items with inventory

---

FrontEnd/frmSetting.Designer.cs
FrontEnd/frmTransaction.Designer.cs
backend/pos-core-api/Controllers/TransactionController.cs
backend/pos-core-api/ORM/TransactionORM.cs
database/Create Inventory.sql
database/Create Inventory_12_28_2020.sql

Allow the commit of unpaid transactions
Update transactions to add Payments and items
Get Suspended transactions

Added suspended transaction logic 

---

FrontEnd/Settings Panels/PanHardware.Designer.cs
FrontEnd/Settings Panels/PanHardware.cs
FrontEnd/Settings Panels/PanReceipt.Designer.cs
FrontEnd/Settings Panels/PanTypes.Designer.cs
FrontEnd/frmSetting.Designer.cs

Formatting issue plus need to fix the appearance tab listbox and picturebox not working after the container was created

update to hardware tab

---

database/Create Inventory_3_11_2021.sql

added use inventory to sql script

Update Create Inventory_3_11_2021.sql

---

FrontEnd/Settings Panels/frmAddPrinter.Designer.cs
FrontEnd/Settings Panels/frmAddPrinter.cs

changed location of clearing out code text boxes to the start of the function

updated add print codes

---

FrontEnd/Settings Panels/PanHardware.Designer.cs
FrontEnd/Settings Panels/PanHardware.cs
FrontEnd/Settings Panels/frmAddPrinter.Designer.cs
FrontEnd/Settings Panels/frmAddPrinter.cs
FrontEnd/Settings Panels/frmAddPrinter.resx
backend/pos-core-api/ORM/PrinterORM.cs
shared/Transaction/Printer.cs

updated populate so that it grabs printer from database after add or update

Settings form

---

FrontEnd/DataAccess.cs

Webserver error fixed

---

FrontEnd/frmCustomer.Designer.cs
FrontEnd/frmCustomer.cs
FrontEnd/frmPropane.Designer.cs
FrontEnd/frmTransaction.cs

added customer search by phone number to customer field

Customer Form fixes

---

FrontEnd/App.config
FrontEnd/SecretCellar.csproj
FrontEnd/frmLookup.Designer.cs
FrontEnd/frmLookup.cs
FrontEnd/packages.config
hardware/NCR_Printer/Printer.csproj
hardware/NCR_Printer/app.config
hardware/NCR_Printer/packages.config
shared/Transaction/Shared.csproj
shared/Transaction/app.config
shared/Transaction/packages.config

show hide working but the update will not add hidden to the item

Updated to lookup formError log

---

FrontEnd/frmCustomer.Designer.cs
FrontEnd/frmLookup.Designer.cs
FrontEnd/frmLookup.cs
FrontEnd/frmPayment.Designer.cs
FrontEnd/frmPayment.cs
FrontEnd/frmTransaction.cs
backend/pos-core-api/pos-core-api.csproj

updated some format issues with customer form added some customer credit functionality to payment form

update to customer form

---

FrontEnd/frmLookup.cs
FrontEnd/frmPayment.Designer.cs
FrontEnd/frmPayment.cs
shared/Transaction/Transaction.cs

credit now added back into credit amount instead of resetting the amount when line is deleted

Error log Payment form

---

FrontEnd/App.config
FrontEnd/SecretCellar.csproj
FrontEnd/frmOrders.Designer.cs
FrontEnd/frmOrders.cs
FrontEnd/packages.config
backend/pos-core-api/pos-core-api.csproj
hardware/NCR_Printer/Printer.csproj
hardware/NCR_Printer/app.config
hardware/NCR_Printer/packages.config
shared/Transaction/Shared.csproj
shared/Transaction/app.config
shared/Transaction/packages.config

Added a history tab to the orders panel to print or view old transactions and receipts

Error log added History to Orders Panel

---

FrontEnd/frmOrders.cs

Still having formatting issue with supplier datagrid won't show currency in price column

Update order total

---

FrontEnd/frmOrders.Designer.cs
FrontEnd/frmOrders.cs
FrontEnd/frmOrders.resx
FrontEnd/frmReceivedOrders.Designer.cs
FrontEnd/frmReceivedOrders.cs

added some functionality to  order received form and fixed supplier and received datagrid so price column is currency format

update to received and bug fix

---

FrontEnd/frmOrders.cs
FrontEnd/frmTransaction.cs
hardware/NCR_Printer/PrintDoc.cs
hardware/NCR_Printer/PurchaseOrder.cs

Finished print order form functionality complete

Update to Print order

---

FrontEnd/frmOrders.Designer.cs
FrontEnd/frmOrders.cs
FrontEnd/frmOrders.resx
FrontEnd/frmReceivedOrders.cs

Tab added to orders to track customer specific orders

Added Customer Order

---

FrontEnd/frmOrders.Designer.cs
FrontEnd/frmOrders.cs
FrontEnd/frmOrders.resx

-Fixed the styling for the order form tabs.

Fixed Styling For Order Form

---

FrontEnd/Orders Panels/Panel_CustomerOrder.Designer.cs
FrontEnd/Orders Panels/Panel_CustomerRequest.Designer.cs
FrontEnd/Orders Panels/Panel_History.Designer.cs
FrontEnd/Orders Panels/Panel_History.resx
FrontEnd/Orders Panels/Panel_SupplierOrder.Designer.cs
FrontEnd/Orders Panels/Panel_SupplierOrder.resx
FrontEnd/frmLookup.Designer.cs
database/Create_Inventory_08_24_2021.sql

Order Panels

---

FrontEnd/Controls/CurrencyBox.cs
FrontEnd/frmLookup.Designer.cs

Left justified and changed cursor position so that it would properly fill the currency correctly

Update to Currency box and Lookup form

---

FrontEnd/frmLookup.cs

Add item button did not reset the search box to blank fixed isssue

Fixed error search box on lookup

---

FrontEnd/Controls/TouchKeyPad.cs
FrontEnd/frmDryCleaning.Designer.cs
FrontEnd/frmDryCleaning.cs
FrontEnd/frmPayment.Designer.cs

Added numeric touchpad to the dry cleaning for and updated layout

dry cleaning form update

---

FrontEnd/Controls/TouchKeyPad.cs
FrontEnd/frmDiscount.Designer.cs
FrontEnd/frmDiscount.cs

fixed issue with keypad and percentage boxes in the keypad control still having issue won't focus on any textbox on form enter

discount form keypad update

---

FrontEnd/frmCustomer.Designer.cs
FrontEnd/frmCustomer.cs
FrontEnd/frmLookup.Designer.cs

Minor UI updates to Customer and Lookup form changed State to bold on customer and adjusted column width on datagrid for lookup form

Customer Lookup UI

---

FrontEnd/Settings Panels/PanEmployee.Designer.cs
FrontEnd/Settings Panels/PanEmployee.cs
backend/pos-core-api/pos-core-api.csproj

added functionality to past employee checkbox

employee panel

---

FrontEnd/Settings Panels/EmployeeTypes.cs
FrontEnd/Settings Panels/PanEmployee.Designer.cs
FrontEnd/Settings Panels/PanEmployee.cs

updates to functionality for both panels

employee and types

---

FrontEnd/DataAccess.cs
FrontEnd/frmTransaction.cs

Wired up the Cash Drawer button for user access

---

FrontEnd/FrmEventsAll.cs
FrontEnd/FrmEventsCreate.cs
FrontEnd/Orders Panels/Panel_Fulfillment.cs
FrontEnd/frmEvents.cs
FrontEnd/frmEventsEdit.cs
FrontEnd/frmEventsWaitList.cs
FrontEnd/frmEventsWaitlistCustomerList.Designer.cs
FrontEnd/frmTransaction.cs

-Added manager override to Fulfillment and Event buttons.

Manager override

---

FrontEnd/frmInvoices.cs

-Changed Update Payment button to be disabled when looking at closed invoices.

Discount price

---

FrontEnd/Settings Panels/PanHardware.Designer.cs
FrontEnd/Settings Panels/PanReceipt.Designer.cs
FrontEnd/Settings Panels/PanReports.Designer.cs
FrontEnd/Settings Panels/PanReports.resx

This reverts commit 9469ac1db167161a12910eb4cdd3c42f3c01c210.

Revert "Cosmetic changes"

---

FrontEnd/Identification.cs
FrontEnd/frmTransaction.cs
shared/Transaction/Transaction.cs

Multiple invoices
